name: PlatformIO CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: infinitecoding/platformio-for-ci:6.1

    strategy:
      matrix:
        env: [arduino, esp8266, esp32]
        example: [examples/get-date-time, examples/set-date-time]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ matrix.env }}-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-${{ matrix.env }}-
            ${{ runner.os }}-platformio-

      - name: Build ${{ matrix.example }} for ${{ matrix.env }}
        run: |
          platformio run -c /opt/build/platformio.ini -d ${{ matrix.example }} -e ${{ matrix.env }}

